#!/bin/bash -e

GREP_OPT='\.c$|\.h$|\.S$|\.cpp$|\.java$|\.lds$|\.chh$|\.cc$|\.py$'

if test -n "$1" -a -d "arch/$1";then
	find . -path "./arch/" -prune -o -print | grep -E $GREP_OPT > cscope.files
	find ./arch/$1 | grep -E $GREP_OPT >> cscope.files
	echo "GEN cscope <- arch/$1"
else
	find . | grep -E $GREP_OPT > cscope.files
	echo "GEN cscope"
fi
(cscope -bq)

(echo "GEN ctags"; ctags -R --fields=+lS)
