"
" Just copy this text document to ~/.vimrc for setting vim
"

if v:lang =~ "utf8$" || v:lang =~ "UTF-8$"
	set fileencodings=utf-8,latin1
endif

set nu
syntax on
set cursorline
set tabstop=4
set shiftwidth=4
set hlsearch
set incsearch
set bg=dark
set history=1024
set wrap
"set nowrap
set noexpandtab
set laststatus=2
set showcmd
set smartcase
set gcr=a:blinkon0
filetype on
filetype plugin indent on
"set statusline=%<%F%h%m%r%h%w%y\ %=\ line:%l\,%L\ %P
set statusline=%<%F%h%m%r%h%w%y\ %{&ff}\ %{strftime(\"%d/%m/%y\ -\ %H:%M\")}%=\ ascii:%b\ lin:%l\,%L\ %P

"del ^M
set fileformat=unix

"ignore case when search
set ignorecase

"switch between two windows, as ctrl+ww
nmap <F4> <C-W>w
nmap <F3> :Tlist<ENTER>
"map <silent> <F4> :TlistToggle<cr>
let Tlist_Exit_OnlyWindow=1
"let Tlist_Use_Right_Window=1
let Tlist_File_Fold_Auto_Close=1

"for NERDTree
nmap <F5> :NERDTree<ENTER>
nmap <F6> :NERDTreeClose<ENTER>
let NERDTreeWinPos='right'

" neocomplcache -> start
let g:neocomplcache_enable_at_startup=1 
let g:NeoComplCache_SmartCase = 1
let g:NeoComplCache_TagsAutoUpdate = 1
let g:NeoComplCache_EnableInfo = 1
let g:NeoComplCache_EnableCamelCaseCompletion = 1
let g:NeoComplCache_MinSyntaxLength = 3
let g:NeoComplCache_EnableSkipCompletion = 1
let g:NeoComplCache_SkipInputTime = '0.5'
let g:NeoComplCache_SnippetsDir = $VIMFILES.'/snippets'
" <TAB> completion.
inoremap <expr><TAB> pumvisible() ? "\<C-n>" : "\<TAB>"
" snippets expand key
imap <silent> <C-e> <Plug>(neocomplcache_snippets_expand)
smap <silent> <C-e> <Plug>(neocomplcache_snippets_expand)

:inoremap ( ()<ESC>i
:inoremap ) <c-r>=ClosePair(')')<CR>
:inoremap { {<CR>}<ESC>O
:inoremap } <c-r>=ClosePair('}')<CR>
:inoremap [ []<ESC>i
:inoremap ] <c-r>=ClosePair(']')<CR>
:inoremap " ""<ESC>i
:inoremap ' ''<ESC>i

function! ClosePair(char)
	if getline('.')[col('.') - 1] == a:char
		return "\<Right>"
	else
		return a:char
	endif
endfunction
" neocomplcache <- end
