"
" Just copy this text document to ~/.vimrc for setting vim
"

if v:lang =~ "utf8$" || v:lang =~ "UTF-8$"
	set fileencodings=utf-8,latin1
endif

set nu
syntax on
set cursorline
highlight CursorLine ctermbg=darkblue ctermfg=grey cterm=bold
"set cursorline cursorcolumn
"highlight CursorColumn ctermbg=darkblue ctermfg=grey cterm=bold
set tabstop=4
set shiftwidth=4
set hlsearch
set incsearch
set bg=dark
set history=1024
set wrap
"set nowrap
set noexpandtab
set laststatus=2
set showcmd
set smartcase
set gcr=a:blinkon0
filetype on
filetype plugin indent on
"set statusline=%<%F%h%m%r%h%w%y\ %=\ line:%l\,%L\ %P
set statusline=%<%F%h%m%r%h%w%y\ %{&ff}\ %{strftime(\"%d/%m/%y\ -\ %H:%M\")}%=\ ascii:%b\ lin:%l\,%L\ %P

"del ^M
set fileformat=unix

"ignore case when search
set ignorecase

"switch between two windows, as ctrl+ww
nmap <F4> <C-W>w
nmap <F3> :Tlist<ENTER>
"map <silent> <F4> :TlistToggle<cr>
let Tlist_Exit_OnlyWindow=1
"let Tlist_Use_Right_Window=1
let Tlist_File_Fold_Auto_Close=1

"for NERDTree
nmap <F5> :NERDTree<ENTER>
nmap <F6> :NERDTreeClose<ENTER>
let NERDTreeWinPos='right'

set list
set listchars=tab:¦\ ,trail:~,extends:»,precedes:«
